"""
Core domain models for ContextWeaver.

These Pydantic models are the lingua franca between all agents, storage layers,
API endpoints, and CLI commands.
"""

from __future__ import annotations

import hashlib
from datetime import datetime
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field, model_validator


class ArtifactKind(StrEnum):
    COMMIT = "commit"
    PR = "pull_request"
    ISSUE = "issue"
    COMMENT = "comment"
    REVIEW = "review"
    DOC = "documentation"
    ADR = "architecture_decision_record"


class DecisionConfidence(StrEnum):
    HIGH = "high"      # Explicitly stated rationale found
    MEDIUM = "medium"  # Inferred from strong contextual signals
    LOW = "low"        # Weak inference, needs human validation


class RawArtifact(BaseModel):
    """A single, unprocessed project artifact (commit, PR, issue, etc.)"""

    kind: ArtifactKind
    source_id: str = Field(description="Provider-specific ID (e.g. GitHub PR number)")
    url: str = Field(default="")
    title: str = Field(default="")
    body: str = Field(default="")
    author: str = Field(default="")
    created_at: datetime
    metadata: dict[str, Any] = Field(default_factory=dict)

    @property
    def content_hash(self) -> str:
        raw = f"{self.kind}:{self.source_id}:{self.body}"
        return hashlib.sha256(raw.encode()).hexdigest()[:16]


class Decision(BaseModel):
    """
    A reconstructed project decision with full archaeological context.

    This is the core unit of ContextWeaver. Every Decision captures not just
    WHAT was decided, but WHY, by whom, when, what alternatives were
    considered, and what trade-offs were accepted.
    """

    id: str = Field(description="Unique decision identifier (content hash)")
    title: str
    summary: str = Field(description="Plain-English summary of the decision")
    rationale: str = Field(description="Reconstructed WHY - the reasoning behind it")
    alternatives_considered: list[str] = Field(
        default_factory=list,
        description="Other options that were explicitly or implicitly evaluated",
    )
    trade_offs: list[str] = Field(
        default_factory=list,
        description="Known downsides or trade-offs accepted",
    )
    confidence: DecisionConfidence = DecisionConfidence.MEDIUM
    authors: list[str] = Field(default_factory=list)
    made_at: datetime
    source_artifacts: list[str] = Field(
        default_factory=list,
        description="IDs/URLs of artifacts this decision was reconstructed from",
    )
    tags: list[str] = Field(
        default_factory=list,
        description="Semantic tags: e.g. ['architecture', 'security', 'performance']",
    )
    superseded_by: str | None = Field(
        default=None,
        description="ID of a newer Decision that replaces this one",
    )
    debt_score: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="0=healthy, 1=critical decision debt (outdated/undocumented)",
    )
    embedding_id: str | None = Field(
        default=None,
        description="ChromaDB document ID for semantic search",
    )

    @model_validator(mode="after")
    def generate_id_if_missing(self) -> "Decision":
        if not self.id:
            raw = f"{self.title}:{self.made_at.isoformat()}"
            self.id = hashlib.sha256(raw.encode()).hexdigest()[:20]
        return self


class ConflictReport(BaseModel):
    """
    A detected conflict between incoming work and a historical decision.
    Generated by the ConflictDetectorAgent during PR/commit analysis.
    """

    artifact_id: str = Field(description="The PR/commit being analyzed")
    conflicting_decision_id: str
    similarity_score: float = Field(ge=0.0, le=1.0)
    explanation: str = Field(
        description="Human-readable explanation of why this is a conflict"
    )
    severity: str = Field(
        default="medium",
        description="low | medium | high | critical",
    )
    suggested_action: str = Field(
        description="What the developer should do to resolve this"
    )
    detected_at: datetime = Field(default_factory=datetime.utcnow)


class ContextBriefing(BaseModel):
    """
    A living, auto-generated context briefing for a developer or task.
    Generated by the BriefingAgent when someone joins a project or starts a feature.
    """

    subject: str = Field(description="Who or what this briefing is for")
    scope: str = Field(description="Repo, module, or topic scope")
    generated_at: datetime = Field(default_factory=datetime.utcnow)

    key_decisions: list[Decision] = Field(
        description="The most relevant historical decisions for this context"
    )
    critical_constraints: list[str] = Field(
        description="Hard limits that must not be violated (security, compliance, etc.)"
    )
    active_debt: list[str] = Field(
        description="Decision debt items that need attention in this area"
    )
    narrative: str = Field(
        description="A flowing narrative briefing that reads like an expert explanation"
    )
    suggested_questions: list[str] = Field(
        description="Questions the developer should ask before proceeding"
    )


class MiningStatus(BaseModel):
    """Progress tracking for an artifact mining run."""

    repo: str
    started_at: datetime = Field(default_factory=datetime.utcnow)
    artifacts_processed: int = 0
    decisions_extracted: int = 0
    errors: int = 0
    completed: bool = False
    completed_at: datetime | None = None
